### ISSUE TITLE
Cannot set strain threshold modifier on gear

### ISSUE THREAD

**Issue by taralx** [Unbound-Legends/RPG-Web-Character-Creator#24]
**Describe the bug**
Strain threshold modifier is ignored on gear.

**To Reproduce**
1. Create custom gear with Modifier: yes, Attribute: Strain Threshold, Modifier Value: 1
2. Add gear to character

**Expected behavior**
Strain threshold increased.

**Additional context**
I suspect it gets clobbered here: https://github.com/SkyJedi/RPG-Web-Character-Creator/blob/32881473fd5f9a83abbd5ff49c134b07ca8647b1/src/components/CustomData/CustomEquipment.js#L64

**Comment by taralx** [comment]
(Also, it would be nice if I could set multiple modifiers on gear/talents...)

**Comment by ShaneK** [comment]
Hey, you were right! That was absolutely it. Sorry it took so long to get fixed! Should be live in a couple minutes.
