### ISSUE TITLE
Convert to nx project

### ISSUE THREAD

**Issue by ShaneK** [Unbound-Legends/RPG-Web-Character-Creator#27]
We plan to convert this project to an nx project for future easier development and access to tooling. This will be a decent sized undertaking, but should pay off in the long run.

**Comment by HolmstN** [comment]
Hi there :)  

I haven't heard of 'nx' before so did a little research. Monorepos in my experience usually lead to difficult development experiences and a lot of married dependencies that become difficult to manage.

Generally I've found a higher separation of concerns to be a better approach, esp. when considering serverless.  Can use something like kubernetes/docker to contain individual applications and develop each repo independently, with its own dependency management and deployment/release cadence.

For similar features to a "monorepo" but without hard interdependencies that NX seems to require, I might recommend Yarn workspaces, which should solve the same problems I think you're hoping to solve for NX.

**Comment by ShaneK** [comment]
I use nx in both my real work and on RPG Sessions and it provides many benefits that don't become hard to manage at all. In fact, the ability to share resources between projects is a real godsend, especially when using interfaces that are shared between projects.

I have a lot of experience with nx, as does @dallastjames, and it really doesn't create the issues you propose it might. It additionally provides really nice tooling for testing, both e2e and integration tests.

**Comment by HolmstN** [comment]
Okay great :)  Maybe NX has solved some of the inherent issues with monorepos then.

**Comment by ShaneK** [comment]
Done!
