### ISSUE TITLE
Set selected character as default on subsequent load

### ISSUE THREAD

**Issue by Stylo101** [Unbound-Legends/RPG-Web-Character-Creator#47]
When loading the emporium, it would be nice if the last character that was being edited were loaded upon logging into the site on a subsequent visit. 

Example: I have three characters

Bob
Garblaxas the Magnificent
Hank

I am editing Garblaxas the Magnificent and log out to go outside to play with my friends. Mom calls me in for dinner and after eating, cleaning the table, and washing under my fingernails, mom lets me get a few moments of screen time, so I go to log back on the emporium and - hey preseto - Garblaxas the Magnificent pops up by default in all of his magnificence.  

Thanks!

**Comment by ShaneK** [comment]
This PR was addressed with #62
